package com.github.kright.pga3d.codegen.cpp

import com.github.kright.pga3d.codegen.common.CodeGen

class CppCodeGen extends CodeGen:
  override val padding: String = " ".repeat(4)

  def pragmaOnce(): Unit = {
    apply("#pragma once")
    apply("")
  }

  def generatedBy(name: String): Unit = {
    apply(s"// generated by ${name}")
    apply("")
  }

  def namespace(name: String)(addCode: => Unit): Unit = {
    apply(s"namespace $name {")
    block {
      addCode
    }
    apply("}")
  }

  def struct(name: String)(addCode: => Unit): Unit = {
    apply(s"struct $name {")
    block {
      addCode
    }
    apply("};")
  }
