package com.github.kright.pga3d.codegen.cpp

import com.github.kright.pga3d.codegen.common.CodeBuilder

class CppCodeBuilder extends CodeBuilder:
  override val padding: String = " ".repeat(4)

  def pragmaOnce(): Unit = {
    apply("#pragma once")
  }

  def licenseMit(): Unit = {
    apply("// Copyright (c) 2025 Igor Slobodskov")
    apply("// SPDX-License-Identifier: MIT")
  }

  def generatedBy(name: String): Unit = {
    apply(s"// generated by ${name}")
  }

  private def normalizedInclude(include: String): String = {
    if (include.startsWith("#include ")) return include
    require(include.startsWith("<") || include.startsWith("\""))
    s"#include ${include}"
  }

  def myHeader(includes: Seq[String], generatedByName: String): Unit = {
    licenseMit()
    apply("")
    pragmaOnce()
    apply("")
    if (includes.nonEmpty) {
      includes.foreach(include => apply(normalizedInclude(include)))
      apply("")
    }
    generatedBy(generatedByName)
    apply("")
  }

  def namespace(name: String)(addCode: => Unit): Unit = {
    apply(s"namespace $name {")
    block {
      addCode
    }
    apply("}")
  }

  def struct(name: String)(addCode: => Unit): Unit = {
    apply(s"struct $name {")
    block {
      addCode
    }
    apply("};")
  }
