// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <array>
#include <span>
#include <type_traits>
#include "typesForward.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp

namespace pga3d {
    struct BivectorWeight {
        // generated by com.github.kright.pga3d.codegen.cpp.ops.StructFieldsGenerator

        double wx = 0.0;
        double wy = 0.0;
        double wz = 0.0;

        static constexpr size_t componentsCount = 3;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept { return { wx, wy, wz }; }
        [[nodiscard]] static constexpr BivectorWeight from(const std::array<double, componentsCount>& values) noexcept { return { .wx = values[0], .wy = values[1], .wz = values[2] }; }
        [[nodiscard]] static constexpr BivectorWeight from(const std::span<double, componentsCount>& values) noexcept { return { .wx = values[0], .wy = values[1], .wz = values[2] }; }

        // generated by com.github.kright.pga3d.codegen.cpp.ops.BivectorWeightOpsGenerator

        [[nodiscard]] constexpr Translator exp() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DualOpGenerator

        [[nodiscard]] constexpr BivectorBulk dual() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WeightOpGenerator

        [[nodiscard]] constexpr BivectorWeight weight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseOpGenerator

        [[nodiscard]] constexpr BivectorWeight reverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiReverseOpGenerator

        [[nodiscard]] constexpr BivectorWeight antiReverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ConversionOpGenerator

        [[nodiscard]] constexpr Multivector toMultivector() const noexcept;
        [[nodiscard]] constexpr Motor toMotor() const noexcept;
        [[nodiscard]] constexpr Bivector toBivector() const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator toProjectiveTranslator() const noexcept;
        [[nodiscard]] constexpr Translator toTranslatorUnsafe() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ArithmeticsGenerator

        [[nodiscard]] constexpr BivectorWeight madd(const BivectorWeight& other, double mult) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.NormOpGenerator

        [[nodiscard]] constexpr double normSquare() const noexcept;
        [[nodiscard]] inline double norm() const noexcept;
        [[nodiscard]] inline BivectorWeight normalizedByNorm() const noexcept;
        [[nodiscard]] constexpr double weightNormSquare() const noexcept;
        [[nodiscard]] inline double weightNorm() const noexcept;
        [[nodiscard]] inline BivectorWeight normalizedByWeight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.GeometricOpGenerator

        [[nodiscard]] constexpr Motor geometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Vector geometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight geometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight geometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector geometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Vector geometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiGeometricOpGenerator

        [[nodiscard]] constexpr Motor antiGeometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Quaternion antiGeometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Quaternion antiGeometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight antiGeometric(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal antiGeometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DotOpGenerator

        [[nodiscard]] constexpr BivectorWeight dot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight dot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight dot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight dot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const PlaneIdeal& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiDotOpGenerator

        [[nodiscard]] constexpr Motor antiDot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar antiDot(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Vector antiDot(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr BivectorBulk antiDot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector antiDot(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Vector antiDot(const Point& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar antiDot(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight antiDot(const PseudoScalar& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WedgeOpGenerator

        [[nodiscard]] constexpr Motor wedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Vector wedge(const Plane& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Motor wedge(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight wedge(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight wedge(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector wedge(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const BivectorBulk& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiWedgeOpGenerator

        [[nodiscard]] constexpr ProjectiveTranslator antiWedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const Point& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight antiWedge(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal antiWedge(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.CrossOpGenerator

        [[nodiscard]] constexpr BivectorWeight cross(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const Plane& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const PointCenter& b) const noexcept;
    };

    static_assert(std::is_trivially_copyable_v<BivectorWeight>);
    static_assert(sizeof(BivectorWeight) == 8 * BivectorWeight::componentsCount, "BivectorWeight must be exactly 24 bytes");
}