// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <array>
#include <span>
#include <type_traits>
#include "typesForward.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp

namespace pga3d {
    struct Multivector {
        // generated by com.github.kright.pga3d.codegen.cpp.struct.StructFieldsGenerator

        double s = 0.0;
        double w = 0.0;
        double x = 0.0;
        double y = 0.0;
        double z = 0.0;
        double wx = 0.0;
        double wy = 0.0;
        double wz = 0.0;
        double xy = 0.0;
        double xz = 0.0;
        double yz = 0.0;
        double wxy = 0.0;
        double wxz = 0.0;
        double wyz = 0.0;
        double xyz = 0.0;
        double i = 0.0;

        static constexpr int componentsCount = 16;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept { return { s, w, x, y, z, wx, wy, wz, xy, xz, yz, wxy, wxz, wyz, xyz, i }; }
        [[nodiscard]] static constexpr Multivector from(const std::span<double, componentsCount>& values) noexcept { return { .s = values[0], .w = values[1], .x = values[2], .y = values[3], .z = values[4], .wx = values[5], .wy = values[6], .wz = values[7], .xy = values[8], .xz = values[9], .yz = values[10], .wxy = values[11], .wxz = values[12], .wyz = values[13], .xyz = values[14], .i = values[15] }; }

        // generated by com.github.kright.pga3d.codegen.cpp.binops.DualOpGenerator

        [[nodiscard]] constexpr Multivector dual() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.WeightOpGenerator

        [[nodiscard]] constexpr Multivector weight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.BulkOpGenerator

        [[nodiscard]] constexpr Multivector bulk() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.ReverseOpGenerator

        [[nodiscard]] constexpr Multivector reverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.AntiReverseOpGenerator

        [[nodiscard]] constexpr Multivector antiReverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.ConversionOpGenerator

        [[nodiscard]] constexpr Motor toMotorUnsafe() const noexcept;
        [[nodiscard]] constexpr Plane toPlaneUnsafe() const noexcept;
        [[nodiscard]] constexpr Bivector toBivectorUnsafe() const noexcept;
        [[nodiscard]] constexpr ProjectivePoint toProjectivePointUnsafe() const noexcept;
        [[nodiscard]] constexpr Quaternion toQuaternionUnsafe() const noexcept;
        [[nodiscard]] constexpr Translator toTranslatorUnsafe() const noexcept;
        [[nodiscard]] constexpr Vector toVectorUnsafe() const noexcept;
        [[nodiscard]] constexpr Point toPointUnsafe() const noexcept;
        [[nodiscard]] constexpr PlaneIdeal toPlaneIdealUnsafe() const noexcept;
        [[nodiscard]] constexpr BivectorBulk toBivectorBulkUnsafe() const noexcept;
        [[nodiscard]] constexpr BivectorWeight toBivectorWeightUnsafe() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.ArithmeticsGenerator

        [[nodiscard]] constexpr Multivector madd(const Multivector& other, double mult) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.NormOpGenerator

        [[nodiscard]] constexpr double normSquare() const noexcept;
        [[nodiscard]] inline double norm() const noexcept;
        [[nodiscard]] inline Multivector normalizedByNorm() const noexcept;
        [[nodiscard]] constexpr double bulkNormSquare() const noexcept;
        [[nodiscard]] inline double bulkNorm() const noexcept;
        [[nodiscard]] inline Multivector normalizedByBulk() const noexcept;
        [[nodiscard]] constexpr double weightNormSquare() const noexcept;
        [[nodiscard]] inline double weightNorm() const noexcept;
        [[nodiscard]] inline Multivector normalizedByWeight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.GeometricOpGenerator

        [[nodiscard]] constexpr Multivector geometric(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.AntiGeometricOpGenerator

        [[nodiscard]] constexpr Multivector antiGeometric(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.DotOpGenerator

        [[nodiscard]] constexpr Multivector dot(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.AntiDotOpGenerator

        [[nodiscard]] constexpr Multivector antiDot(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.WedgeOpGenerator

        [[nodiscard]] constexpr Multivector wedge(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.AntiWedgeOpGenerator

        [[nodiscard]] constexpr Multivector antiWedge(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.SandwichOpGenerator

        [[nodiscard]] constexpr Multivector sandwich(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.ReverseSandwichOpGenerator

        [[nodiscard]] constexpr Multivector reverseSandwich(const Multivector& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.binops.CrossOpGenerator

        [[nodiscard]] constexpr Multivector cross(const Multivector& b) const noexcept;
    };

    static_assert(std::is_trivially_copyable_v<Multivector>);
    static_assert(sizeof(Multivector) == 8 * Multivector::componentsCount, "Multivector must be exactly 128 bytes");
}