#pragma once

#include "types.h"
// generated by com.github.kright.pga3d.codegen.cpp.binops.StructStaticConstructorGenerator

namespace pga3d {
    [[nodiscard]] constexpr Translator Translator::addVector(const Vector& v) noexcept { return {.wx = v.x, .wy = v.y, .wz = v.z}; }
}