#pragma once

#include <cmath>
#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.NormOpGenerator

namespace pga3d {
    constexpr double Multivector::normSquare() const noexcept { return (i * i + s * s + w * w + wx * wx + wxy * wxy + wxz * wxz + wy * wy + wyz * wyz + wz * wz + x * x + xy * xy + xyz * xyz + xz * xz + y * y + yz * yz + z * z); }
    double Multivector::norm() const noexcept { return std::sqrt(normSquare()); }
    Multivector Multivector::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Motor::normSquare() const noexcept { return (i * i + s * s + wx * wx + wy * wy + wz * wz + xy * xy + xz * xz + yz * yz); }
    double Motor::norm() const noexcept { return std::sqrt(normSquare()); }
    Motor Motor::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Plane::normSquare() const noexcept { return (w * w + x * x + y * y + z * z); }
    double Plane::norm() const noexcept { return std::sqrt(normSquare()); }
    Plane Plane::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Bivector::normSquare() const noexcept { return (wx * wx + wy * wy + wz * wz + xy * xy + xz * xz + yz * yz); }
    double Bivector::norm() const noexcept { return std::sqrt(normSquare()); }
    Bivector Bivector::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double ProjectivePoint::normSquare() const noexcept { return (w * w + x * x + y * y + z * z); }
    double ProjectivePoint::norm() const noexcept { return std::sqrt(normSquare()); }
    ProjectivePoint ProjectivePoint::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Quaternion::normSquare() const noexcept { return (s * s + xy * xy + xz * xz + yz * yz); }
    double Quaternion::norm() const noexcept { return std::sqrt(normSquare()); }
    Quaternion Quaternion::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Translator::normSquare() const noexcept { return (1.0 + wx * wx + wy * wy + wz * wz); }
    double Translator::norm() const noexcept { return std::sqrt(normSquare()); }
    Motor Translator::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Vector::normSquare() const noexcept { return (x * x + y * y + z * z); }
    double Vector::norm() const noexcept { return std::sqrt(normSquare()); }
    Vector Vector::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double Point::normSquare() const noexcept { return (1.0 + x * x + y * y + z * z); }
    double Point::norm() const noexcept { return std::sqrt(normSquare()); }
    ProjectivePoint Point::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double PlaneIdeal::normSquare() const noexcept { return (x * x + y * y + z * z); }
    double PlaneIdeal::norm() const noexcept { return std::sqrt(normSquare()); }
    PlaneIdeal PlaneIdeal::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double BivectorBulk::normSquare() const noexcept { return (xy * xy + xz * xz + yz * yz); }
    double BivectorBulk::norm() const noexcept { return std::sqrt(normSquare()); }
    BivectorBulk BivectorBulk::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double BivectorWeight::normSquare() const noexcept { return (wx * wx + wy * wy + wz * wz); }
    double BivectorWeight::norm() const noexcept { return std::sqrt(normSquare()); }
    BivectorWeight BivectorWeight::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double PseudoScalar::normSquare() const noexcept { return i * i; }
    double PseudoScalar::norm() const noexcept { return std::sqrt(normSquare()); }
    PseudoScalar PseudoScalar::normalizedByNorm() const noexcept { return *this / norm(); }

    constexpr double PointCenter::normSquare() const noexcept { return 1.0; }
    double PointCenter::norm() const noexcept { return std::sqrt(normSquare()); }
    ProjectivePoint PointCenter::normalizedByNorm() const noexcept { return *this / norm(); }

}