#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.ArithmeticsGenerator

namespace pga3d {
    [[nodiscard]] constexpr Multivector operator+(const Multivector& a, const Multivector& b) noexcept { return {.s = (a.s + b.s), .w = (a.w + b.w), .x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz), .wxy = (a.wxy + b.wxy), .wxz = (a.wxz + b.wxz), .wyz = (a.wyz + b.wyz), .xyz = (a.xyz + b.xyz), .i = (a.i + b.i)}; }
    [[nodiscard]] constexpr Multivector operator-(const Multivector& a, const Multivector& b) noexcept { return {.s = (a.s - b.s), .w = (a.w - b.w), .x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz), .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz), .wxy = (a.wxy - b.wxy), .wxz = (a.wxz - b.wxz), .wyz = (a.wyz - b.wyz), .xyz = (a.xyz - b.xyz), .i = (a.i - b.i)}; }

    [[nodiscard]] constexpr Motor operator+(const Motor& a, const Motor& b) noexcept { return {.s = (a.s + b.s), .wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz), .i = (a.i + b.i)}; }
    [[nodiscard]] constexpr Motor operator-(const Motor& a, const Motor& b) noexcept { return {.s = (a.s - b.s), .wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz), .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz), .i = (a.i - b.i)}; }

    [[nodiscard]] constexpr Plane operator+(const Plane& a, const Plane& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = (a.w + b.w)}; }
    [[nodiscard]] constexpr Plane operator-(const Plane& a, const Plane& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = (a.w - b.w)}; }

    [[nodiscard]] constexpr Bivector operator+(const Bivector& a, const Bivector& b) noexcept { return {.wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz)}; }
    [[nodiscard]] constexpr Bivector operator-(const Bivector& a, const Bivector& b) noexcept { return {.wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz), .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz)}; }
    [[nodiscard]] constexpr Bivector operator+(const Bivector& a, const BivectorBulk& b) noexcept { return {.wx = a.wx, .wy = a.wy, .wz = a.wz, .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz)}; }
    [[nodiscard]] constexpr Bivector operator-(const Bivector& a, const BivectorBulk& b) noexcept { return {.wx = a.wx, .wy = a.wy, .wz = a.wz, .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz)}; }
    [[nodiscard]] constexpr Bivector operator+(const Bivector& a, const BivectorWeight& b) noexcept { return {.wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = a.xy, .xz = a.xz, .yz = a.yz}; }
    [[nodiscard]] constexpr Bivector operator-(const Bivector& a, const BivectorWeight& b) noexcept { return {.wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz), .xy = a.xy, .xz = a.xz, .yz = a.yz}; }

    [[nodiscard]] constexpr ProjectivePoint operator+(const ProjectivePoint& a, const ProjectivePoint& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = (a.w + b.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const ProjectivePoint& a, const ProjectivePoint& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = (a.w - b.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator+(const ProjectivePoint& a, const Point& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = (1.0 + a.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const ProjectivePoint& a, const Point& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = (-1.0 + a.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator+(const ProjectivePoint& a, const Vector& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = a.w}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const ProjectivePoint& a, const Vector& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = a.w}; }

    [[nodiscard]] constexpr Quaternion operator+(const Quaternion& a, const Quaternion& b) noexcept { return {.s = (a.s + b.s), .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz)}; }
    [[nodiscard]] constexpr Quaternion operator-(const Quaternion& a, const Quaternion& b) noexcept { return {.s = (a.s - b.s), .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz)}; }

    [[nodiscard]] constexpr Motor operator+(const Translator& a, const Translator& b) noexcept { return {.s = 2.0, .wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = 0.0, .xz = 0.0, .yz = 0.0, .i = 0.0}; }
    [[nodiscard]] constexpr BivectorWeight operator-(const Translator& a, const Translator& b) noexcept { return {.wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz)}; }

    [[nodiscard]] constexpr ProjectivePoint operator+(const Vector& a, const ProjectivePoint& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = b.w}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const Vector& a, const ProjectivePoint& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = -b.w}; }
    [[nodiscard]] constexpr Point operator+(const Vector& a, const Point& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z)}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const Vector& a, const Point& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = -1.0}; }
    [[nodiscard]] constexpr Vector operator+(const Vector& a, const Vector& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z)}; }
    [[nodiscard]] constexpr Vector operator-(const Vector& a, const Vector& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z)}; }

    [[nodiscard]] constexpr ProjectivePoint operator+(const Point& a, const ProjectivePoint& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = (1.0 + b.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator-(const Point& a, const ProjectivePoint& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z), .w = (1.0 - b.w)}; }
    [[nodiscard]] constexpr ProjectivePoint operator+(const Point& a, const Point& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z), .w = 2.0}; }
    [[nodiscard]] constexpr Vector operator-(const Point& a, const Point& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z)}; }
    [[nodiscard]] constexpr Point operator+(const Point& a, const Vector& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z)}; }
    [[nodiscard]] constexpr Point operator-(const Point& a, const Vector& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z)}; }

    [[nodiscard]] constexpr PlaneIdeal operator+(const PlaneIdeal& a, const PlaneIdeal& b) noexcept { return {.x = (a.x + b.x), .y = (a.y + b.y), .z = (a.z + b.z)}; }
    [[nodiscard]] constexpr PlaneIdeal operator-(const PlaneIdeal& a, const PlaneIdeal& b) noexcept { return {.x = (a.x - b.x), .y = (a.y - b.y), .z = (a.z - b.z)}; }

    [[nodiscard]] constexpr Bivector operator+(const BivectorBulk& a, const Bivector& b) noexcept { return {.wx = b.wx, .wy = b.wy, .wz = b.wz, .xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz)}; }
    [[nodiscard]] constexpr Bivector operator-(const BivectorBulk& a, const Bivector& b) noexcept { return {.wx = -b.wx, .wy = -b.wy, .wz = -b.wz, .xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz)}; }
    [[nodiscard]] constexpr BivectorBulk operator+(const BivectorBulk& a, const BivectorBulk& b) noexcept { return {.xy = (a.xy + b.xy), .xz = (a.xz + b.xz), .yz = (a.yz + b.yz)}; }
    [[nodiscard]] constexpr BivectorBulk operator-(const BivectorBulk& a, const BivectorBulk& b) noexcept { return {.xy = (a.xy - b.xy), .xz = (a.xz - b.xz), .yz = (a.yz - b.yz)}; }
    [[nodiscard]] constexpr Bivector operator+(const BivectorBulk& a, const BivectorWeight& b) noexcept { return {.wx = b.wx, .wy = b.wy, .wz = b.wz, .xy = a.xy, .xz = a.xz, .yz = a.yz}; }
    [[nodiscard]] constexpr Bivector operator-(const BivectorBulk& a, const BivectorWeight& b) noexcept { return {.wx = -b.wx, .wy = -b.wy, .wz = -b.wz, .xy = a.xy, .xz = a.xz, .yz = a.yz}; }

    [[nodiscard]] constexpr Bivector operator+(const BivectorWeight& a, const Bivector& b) noexcept { return {.wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz), .xy = b.xy, .xz = b.xz, .yz = b.yz}; }
    [[nodiscard]] constexpr Bivector operator-(const BivectorWeight& a, const Bivector& b) noexcept { return {.wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz), .xy = -b.xy, .xz = -b.xz, .yz = -b.yz}; }
    [[nodiscard]] constexpr Bivector operator+(const BivectorWeight& a, const BivectorBulk& b) noexcept { return {.wx = a.wx, .wy = a.wy, .wz = a.wz, .xy = b.xy, .xz = b.xz, .yz = b.yz}; }
    [[nodiscard]] constexpr Bivector operator-(const BivectorWeight& a, const BivectorBulk& b) noexcept { return {.wx = a.wx, .wy = a.wy, .wz = a.wz, .xy = -b.xy, .xz = -b.xz, .yz = -b.yz}; }
    [[nodiscard]] constexpr BivectorWeight operator+(const BivectorWeight& a, const BivectorWeight& b) noexcept { return {.wx = (a.wx + b.wx), .wy = (a.wy + b.wy), .wz = (a.wz + b.wz)}; }
    [[nodiscard]] constexpr BivectorWeight operator-(const BivectorWeight& a, const BivectorWeight& b) noexcept { return {.wx = (a.wx - b.wx), .wy = (a.wy - b.wy), .wz = (a.wz - b.wz)}; }

    [[nodiscard]] constexpr PseudoScalar operator+(const PseudoScalar& a, const PseudoScalar& b) noexcept { return {.i = (a.i + b.i)}; }
    [[nodiscard]] constexpr PseudoScalar operator-(const PseudoScalar& a, const PseudoScalar& b) noexcept { return {.i = (a.i - b.i)}; }

    [[nodiscard]] constexpr ProjectivePoint operator+(const PointCenter& a, const PointCenter& b) noexcept { return {.x = 0.0, .y = 0.0, .z = 0.0, .w = 2.0}; }

}