#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.BivectorWeightOpsGenerator

namespace pga3d {

    [[nodiscard]] inline Translator BivectorWeight::exp() const noexcept {
        return Translator{
            .wx = wx,
            .wy = wy,
            .wz = wz,
        };
    }
}