// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.AntiGeometricOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::antiGeometric(const Multivector& b) const noexcept { return {
        .s = (b.i * s + b.s * i + b.w * xyz + b.wx * yz + b.wxy * z + b.wyz * x + b.wz * xy + b.xy * wz + b.y * wxz + b.yz * wx - b.wxz * y - b.wy * xz - b.x * wyz - b.xyz * w - b.xz * wy - b.z * wxy),
        .w = (b.i * w + b.w * i + b.wxz * wy + b.wy * wxz - b.wx * wyz - b.wxy * wz - b.wyz * wx - b.wz * wxy),
        .x = (b.i * x + b.wxz * xy + b.wy * z + b.wyz * s + b.x * i + b.xy * wxz + b.y * wz + b.yz * w - b.s * wyz - b.w * yz - b.wx * xyz - b.wxy * xz - b.wz * y - b.xyz * wx - b.xz * wxy - b.z * wy),
        .y = (b.i * y + b.s * wxz + b.w * xz + b.wyz * xy + b.wz * x + b.xy * wyz + b.y * i + b.z * wx - b.wx * z - b.wxy * yz - b.wxz * s - b.wy * xyz - b.x * wz - b.xyz * wy - b.xz * w - b.yz * wxy),
        .z = (b.i * z + b.wx * y + b.wxy * s + b.wyz * xz + b.x * wy + b.xy * w + b.xz * wyz + b.z * i - b.s * wxy - b.w * xy - b.wxz * yz - b.wy * x - b.wz * xyz - b.xyz * wz - b.y * wx - b.yz * wxz),
        .wx = (b.i * wx + b.wx * i + b.wxz * wxy + b.wy * wz - b.w * wyz - b.wxy * wxz - b.wyz * w - b.wz * wy),
        .wy = (b.i * wy + b.w * wxz + b.wxz * w + b.wy * i + b.wyz * wxy + b.wz * wx - b.wx * wz - b.wxy * wyz),
        .wz = (b.i * wz + b.wx * wy + b.wyz * wxz + b.wz * i - b.w * wxy - b.wxy * w - b.wxz * wyz - b.wy * wx),
        .xy = (b.i * xy + b.w * z + b.wxz * x + b.wyz * y + b.x * wxz + b.xy * i + b.xyz * wxy + b.xz * wx + b.y * wyz + b.yz * wy - b.s * wz - b.wx * xz - b.wxy * xyz - b.wy * yz - b.wz * s - b.z * w),
        .xz = (b.i * xz + b.s * wy + b.wx * xy + b.wy * s + b.wyz * z + b.xyz * wxz + b.xz * i + b.y * w + b.yz * wz + b.z * wyz - b.w * y - b.wxy * x - b.wxz * xyz - b.wz * yz - b.x * wxy - b.xy * wx),
        .yz = (b.i * yz + b.w * x + b.wy * xy + b.wz * xz + b.xyz * wyz + b.yz * i - b.s * wx - b.wx * s - b.wxy * y - b.wxz * z - b.wyz * xyz - b.x * w - b.xy * wy - b.xz * wz - b.y * wxy - b.z * wxz),
        .wxy = (b.i * wxy + b.w * wz + b.wxy * i + b.wxz * wx + b.wyz * wy + b.wz * w - b.wx * wxz - b.wy * wyz),
        .wxz = (b.i * wxz + b.wx * wxy + b.wxz * i + b.wyz * wz - b.w * wy - b.wxy * wx - b.wy * w - b.wz * wyz),
        .wyz = (b.i * wyz + b.w * wx + b.wx * w + b.wy * wxy + b.wyz * i + b.wz * wxz - b.wxy * wy - b.wxz * wz),
        .xyz = (b.i * xyz + b.s * w + b.wx * x + b.wy * y + b.wz * z + b.x * wx + b.xy * wxy + b.xyz * i + b.xz * wxz + b.y * wy + b.yz * wyz + b.z * wz - b.w * s - b.wxy * xy - b.wxz * xz - b.wyz * yz),
        .i = (b.i * i + b.wxy * wxy + b.wxz * wxz + b.wyz * wyz - b.w * w - b.wx * wx - b.wy * wy - b.wz * wz)
    }; }


    constexpr Motor Motor::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.i * s + b.s * i + b.wx * yz + b.wz * xy + b.xy * wz + b.yz * wx - b.wy * xz - b.xz * wy),
        .wx = (b.i * wx + b.wx * i + b.wy * wz - b.wz * wy),
        .wy = (b.i * wy + b.wy * i + b.wz * wx - b.wx * wz),
        .wz = (b.i * wz + b.wx * wy + b.wz * i - b.wy * wx),
        .xy = (b.i * xy + b.xy * i + b.xz * wx + b.yz * wy - b.s * wz - b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.i * xz + b.s * wy + b.wx * xy + b.wy * s + b.xz * i + b.yz * wz - b.wz * yz - b.xy * wx),
        .yz = (b.i * yz + b.wy * xy + b.wz * xz + b.yz * i - b.s * wx - b.wx * s - b.xy * wy - b.xz * wz),
        .i = (b.i * i - b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Motor::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = b.w * i,
        .x = (b.x * i + b.y * wz - b.w * yz - b.z * wy),
        .y = (b.w * xz + b.y * i + b.z * wx - b.x * wz),
        .z = (b.x * wy + b.z * i - b.w * xy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.w * wz,
        .wxz = -b.w * wy,
        .wyz = b.w * wx,
        .xyz = (b.x * wx + b.y * wy + b.z * wz - b.w * s),
        .i = 0.0
    }; }

    constexpr Motor Motor::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy + b.xy * wz + b.yz * wx - b.wy * xz - b.xz * wy),
        .wx = (b.wx * i + b.wy * wz - b.wz * wy),
        .wy = (b.wy * i + b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy + b.wz * i - b.wy * wx),
        .xy = (b.xy * i + b.xz * wx + b.yz * wy - b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s + b.xz * i + b.yz * wz - b.wz * yz - b.xy * wx),
        .yz = (b.wy * xy + b.wz * xz + b.yz * i - b.wx * s - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Motor::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (b.y * xy + b.z * xz - b.w * wx - b.x * s),
        .y = (b.z * yz - b.w * wy - b.x * xy - b.y * s),
        .z = (-b.w * wz - b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy - b.z * i),
        .wxz = (b.y * i + b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.x * i - b.y * wz),
        .xyz = (b.w * i + b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion Motor::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = (b.s * i + b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xy * i + b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.xz * i + b.yz * wz - b.xy * wx),
        .yz = (b.yz * i - b.s * wx - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Motor::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = (b.s * i + b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wx * i + b.wy * wz - b.wz * wy),
        .wy = (b.wy * i + b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy + b.wz * i - b.wy * wx),
        .xy = (-b.s * wz - b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.s * wy + b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.s * wx - b.wx * s),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor Motor::antiGeometric(const Translator& b) const noexcept { return {
        .s = (i + b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wx * i + b.wy * wz - b.wz * wy),
        .wy = (b.wy * i + b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy + b.wz * i - b.wy * wx),
        .xy = (-wz - b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (wy + b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (-wx + b.wy * xy + b.wz * xz - b.wx * s),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Motor::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (b.y * xy + b.z * xz - b.x * s),
        .y = (b.z * yz - b.x * xy - b.y * s),
        .z = (-b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy - b.z * i),
        .wxz = (b.y * i + b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.x * i - b.y * wz),
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector Motor::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-wx + b.y * xy + b.z * xz - b.x * s),
        .y = (-wy + b.z * yz - b.x * xy - b.y * s),
        .z = (-wz - b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy - b.z * i),
        .wxz = (b.y * i + b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.x * i - b.y * wz),
        .xyz = (i + b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector Motor::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.x * i + b.y * wz - b.z * wy),
        .y = (b.y * i + b.z * wx - b.x * wz),
        .z = (b.x * wy + b.z * i - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Quaternion Motor::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xy * i + b.xz * wx + b.yz * wy),
        .xz = (b.xz * i + b.yz * wz - b.xy * wx),
        .yz = (b.yz * i - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Motor::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wx * i + b.wy * wz - b.wz * wy),
        .wy = (b.wy * i + b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy + b.wz * i - b.wy * wx),
        .xy = (-b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.wx * s),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor Motor::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .s = b.i * s,
        .wx = b.i * wx,
        .wy = b.i * wy,
        .wz = b.i * wz,
        .xy = b.i * xy,
        .xz = b.i * xz,
        .yz = b.i * yz,
        .i = b.i * i
    }; }

    constexpr Multivector Motor::antiGeometric(const PointCenter& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = -wx,
        .y = -wy,
        .z = -wz,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = i,
        .i = 0.0
    }; }


    constexpr Multivector Plane::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = b.i * w,
        .x = (b.i * x + b.wy * z + b.yz * w - b.wz * y),
        .y = (b.i * y + b.wz * x - b.wx * z - b.xz * w),
        .z = (b.i * z + b.wx * y + b.xy * w - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.wz * w,
        .wxz = -b.wy * w,
        .wyz = b.wx * w,
        .xyz = (b.s * w + b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Motor Plane::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = (b.w * z - b.z * w),
        .xz = (b.y * w - b.w * y),
        .yz = (b.w * x - b.x * w),
        .i = -b.w * w
    }; }

    constexpr Multivector Plane::antiGeometric(const Bivector& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z + b.yz * w - b.wz * y),
        .y = (b.wz * x - b.wx * z - b.xz * w),
        .z = (b.wx * y + b.xy * w - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.wz * w,
        .wxz = -b.wy * w,
        .wyz = b.wx * w,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Motor Plane::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = (-b.w * w - b.x * x - b.y * y - b.z * z),
        .wx = b.x * w,
        .wy = b.y * w,
        .wz = b.z * w,
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z),
        .i = 0.0
    }; }

    constexpr Multivector Plane::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = b.yz * w,
        .y = -b.xz * w,
        .z = b.xy * w,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = b.s * w,
        .i = 0.0
    }; }

    constexpr Multivector Plane::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.wz * w,
        .wxz = -b.wy * w,
        .wyz = b.wx * w,
        .xyz = (b.s * w + b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Multivector Plane::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.wz * w,
        .wxz = -b.wy * w,
        .wyz = b.wx * w,
        .xyz = (w + b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Motor Plane::antiGeometric(const Vector& b) const noexcept { return {
        .s = (-b.x * x - b.y * y - b.z * z),
        .wx = b.x * w,
        .wy = b.y * w,
        .wz = b.z * w,
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z),
        .i = 0.0
    }; }

    constexpr Motor Plane::antiGeometric(const Point& b) const noexcept { return {
        .s = (-w - b.x * x - b.y * y - b.z * z),
        .wx = b.x * w,
        .wy = b.y * w,
        .wz = b.z * w,
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z),
        .i = 0.0
    }; }

    constexpr BivectorBulk Plane::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .xy = -b.z * w,
        .xz = b.y * w,
        .yz = -b.x * w
    }; }

    constexpr PlaneIdeal Plane::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .x = b.yz * w,
        .y = -b.xz * w,
        .z = b.xy * w
    }; }

    constexpr Multivector Plane::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.wz * w,
        .wxz = -b.wy * w,
        .wyz = b.wx * w,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Plane Plane::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = b.i * x,
        .y = b.i * y,
        .z = b.i * z,
        .w = b.i * w
    }; }

    constexpr double Plane::antiGeometric(const PointCenter& b) const noexcept { return -w; }


    constexpr Motor Bivector::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy + b.xy * wz + b.yz * wx - b.wy * xz - b.xz * wy),
        .wx = (b.i * wx + b.wy * wz - b.wz * wy),
        .wy = (b.i * wy + b.wz * wx - b.wx * wz),
        .wz = (b.i * wz + b.wx * wy - b.wy * wx),
        .xy = (b.i * xy + b.xz * wx + b.yz * wy - b.s * wz - b.wx * xz - b.wy * yz),
        .xz = (b.i * xz + b.s * wy + b.wx * xy + b.yz * wz - b.wz * yz - b.xy * wx),
        .yz = (b.i * yz + b.wy * xy + b.wz * xz - b.s * wx - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Bivector::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.w * yz - b.z * wy),
        .y = (b.w * xz + b.z * wx - b.x * wz),
        .z = (b.x * wy - b.w * xy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.w * wz,
        .wxz = -b.w * wy,
        .wyz = b.w * wx,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Motor Bivector::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy + b.xy * wz + b.yz * wx - b.wy * xz - b.xz * wy),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (b.xz * wx + b.yz * wy - b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy + b.yz * wz - b.wz * yz - b.xy * wx),
        .yz = (b.wy * xy + b.wz * xz - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Bivector::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (b.y * xy + b.z * xz - b.w * wx),
        .y = (b.z * yz - b.w * wy - b.x * xy),
        .z = (-b.w * wz - b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion Bivector::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Bivector::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.s * wz - b.wx * xz - b.wy * yz),
        .xz = (b.s * wy + b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.s * wx),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor Bivector::antiGeometric(const Translator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-wz - b.wx * xz - b.wy * yz),
        .xz = (wy + b.wx * xy - b.wz * yz),
        .yz = (-wx + b.wy * xy + b.wz * xz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Bivector::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (b.y * xy + b.z * xz),
        .y = (b.z * yz - b.x * xy),
        .z = (-b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector Bivector::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-wx + b.y * xy + b.z * xz),
        .y = (-wy + b.z * yz - b.x * xy),
        .z = (-wz - b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector Bivector::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Quaternion Bivector::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy),
        .xz = (b.yz * wz - b.xy * wx),
        .yz = (-b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Bivector::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Bivector Bivector::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .wx = b.i * wx,
        .wy = b.i * wy,
        .wz = b.i * wz,
        .xy = b.i * xy,
        .xz = b.i * xz,
        .yz = b.i * yz
    }; }

    constexpr PlaneIdeal Bivector::antiGeometric(const PointCenter& b) const noexcept { return {
        .x = -wx,
        .y = -wy,
        .z = -wz
    }; }


    constexpr Multivector ProjectivePoint::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (b.s * x + b.xy * y + b.xz * z - b.wx * w),
        .y = (b.s * y + b.yz * z - b.wy * w - b.xy * x),
        .z = (b.s * z - b.wz * w - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.i * z - b.wx * y),
        .wxz = (b.i * y + b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.i * x - b.wy * z),
        .xyz = (b.i * w + b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor ProjectivePoint::antiGeometric(const Plane& b) const noexcept { return {
        .s = (b.w * w + b.x * x + b.y * y + b.z * z),
        .wx = b.w * x,
        .wy = b.w * y,
        .wz = b.w * z,
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y),
        .i = 0.0
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const Bivector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (b.xy * y + b.xz * z - b.wx * w),
        .y = (b.yz * z - b.wy * w - b.xy * x),
        .z = (-b.wz * w - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor ProjectivePoint::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = (b.z * w - b.w * z),
        .xz = (b.w * y - b.y * w),
        .yz = (b.x * w - b.w * x),
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.s * x + b.xy * y + b.xz * z),
        .y = (b.s * y + b.yz * z - b.xy * x),
        .z = (b.s * z - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (b.s * x - b.wx * w),
        .y = (b.s * y - b.wy * w),
        .z = (b.s * z - b.wz * w),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (x - b.wx * w),
        .y = (y - b.wy * w),
        .z = (z - b.wz * w),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Motor ProjectivePoint::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = b.z * w,
        .xz = -b.y * w,
        .yz = b.x * w,
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Motor ProjectivePoint::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = (-z + b.z * w),
        .xz = (y - b.y * w),
        .yz = (-x + b.x * w),
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Quaternion ProjectivePoint::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = (b.x * x + b.y * y + b.z * z),
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y)
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.xy * y + b.xz * z),
        .y = (b.yz * z - b.xy * x),
        .z = (-b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector ProjectivePoint::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = -b.wx * w,
        .y = -b.wy * w,
        .z = -b.wz * w,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr ProjectivePoint ProjectivePoint::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = b.i * x,
        .y = b.i * y,
        .z = b.i * z,
        .w = b.i * w
    }; }

    constexpr BivectorBulk ProjectivePoint::antiGeometric(const PointCenter& b) const noexcept { return {
        .xy = -z,
        .xz = y,
        .yz = -x
    }; }


    constexpr Quaternion Quaternion::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.i * s + b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (b.i * xy - b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.i * xz + b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.i * yz + b.wy * xy + b.wz * xz - b.wx * s)
    }; }

    constexpr Multivector Quaternion::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = -b.w * yz,
        .y = b.w * xz,
        .z = -b.w * xy,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = -b.w * s,
        .i = 0.0
    }; }

    constexpr Quaternion Quaternion::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.wx * s)
    }; }

    constexpr Multivector Quaternion::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz - b.x * s),
        .y = (b.z * yz - b.x * xy - b.y * s),
        .z = (-b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion Quaternion::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.wx * s)
    }; }

    constexpr Quaternion Quaternion::antiGeometric(const Translator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.wx * s)
    }; }

    constexpr Multivector Quaternion::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz - b.x * s),
        .y = (b.z * yz - b.x * xy - b.y * s),
        .z = (-b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector Quaternion::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz - b.x * s),
        .y = (b.z * yz - b.x * xy - b.y * s),
        .z = (-b.x * xz - b.y * yz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion Quaternion::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz - b.wz * s),
        .xz = (b.wx * xy + b.wy * s - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz - b.wx * s)
    }; }

    constexpr Quaternion Quaternion::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .s = b.i * s,
        .xy = b.i * xy,
        .xz = b.i * xz,
        .yz = b.i * yz
    }; }


    constexpr Motor ProjectiveTranslator::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.i * s + b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.i * wx + b.wy * wz - b.wz * wy),
        .wy = (b.i * wy + b.wz * wx - b.wx * wz),
        .wz = (b.i * wz + b.wx * wy - b.wy * wx),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz - b.wz * s),
        .xz = (b.s * wy + b.wy * s + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.wx * s - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector ProjectiveTranslator::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.w * wz,
        .wxz = -b.w * wy,
        .wyz = b.w * wx,
        .xyz = (b.x * wx + b.y * wy + b.z * wz - b.w * s),
        .i = 0.0
    }; }

    constexpr Motor ProjectiveTranslator::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (b.xz * wx + b.yz * wy - b.wz * s),
        .xz = (b.wy * s + b.yz * wz - b.xy * wx),
        .yz = (-b.wx * s - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector ProjectiveTranslator::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-b.w * wx - b.x * s),
        .y = (-b.w * wy - b.y * s),
        .z = (-b.w * wz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Quaternion ProjectiveTranslator::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor ProjectiveTranslator::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.s * wz - b.wz * s),
        .xz = (b.s * wy + b.wy * s),
        .yz = (-b.s * wx - b.wx * s),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor ProjectiveTranslator::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-wz - b.wz * s),
        .xz = (wy + b.wy * s),
        .yz = (-wx - b.wx * s),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector ProjectiveTranslator::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = -b.x * s,
        .y = -b.y * s,
        .z = -b.z * s,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector ProjectiveTranslator::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-wx - b.x * s),
        .y = (-wy - b.y * s),
        .z = (-wz - b.z * s),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector ProjectiveTranslator::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Quaternion ProjectiveTranslator::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy),
        .xz = (b.yz * wz - b.xy * wx),
        .yz = (-b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor ProjectiveTranslator::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = -b.wz * s,
        .xz = b.wy * s,
        .yz = -b.wx * s,
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr ProjectiveTranslator ProjectiveTranslator::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .s = b.i * s,
        .wx = b.i * wx,
        .wy = b.i * wy,
        .wz = b.i * wz
    }; }

    constexpr PlaneIdeal ProjectiveTranslator::antiGeometric(const PointCenter& b) const noexcept { return {
        .x = -wx,
        .y = -wy,
        .z = -wz
    }; }


    constexpr Motor Translator::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.i + b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.i * wx + b.wy * wz - b.wz * wy),
        .wy = (b.i * wy + b.wz * wx - b.wx * wz),
        .wz = (b.i * wz + b.wx * wy - b.wy * wx),
        .xy = (-b.wz + b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.wy + b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.wx - b.s * wx - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Translator::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.w * wz,
        .wxz = -b.w * wy,
        .wyz = b.w * wx,
        .xyz = (-b.w + b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Motor Translator::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.wz + b.xz * wx + b.yz * wy),
        .xz = (b.wy + b.yz * wz - b.xy * wx),
        .yz = (-b.wx - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Translator::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-b.x - b.w * wx),
        .y = (-b.y - b.w * wy),
        .z = (-b.z - b.w * wz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Quaternion Translator::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Translator::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.wz - b.s * wz),
        .xz = (b.wy + b.s * wy),
        .yz = (-b.wx - b.s * wx),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor Translator::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (-b.wz - wz),
        .xz = (b.wy + wy),
        .yz = (-b.wx - wx),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector Translator::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = -b.x,
        .y = -b.y,
        .z = -b.z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector Translator::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = (-b.x - wx),
        .y = (-b.y - wy),
        .z = (-b.z - wz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector Translator::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Quaternion Translator::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy),
        .xz = (b.yz * wz - b.xy * wx),
        .yz = (-b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor Translator::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = -b.wz,
        .xz = b.wy,
        .yz = -b.wx,
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr ProjectiveTranslator Translator::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .s = b.i,
        .wx = b.i * wx,
        .wy = b.i * wy,
        .wz = b.i * wz
    }; }

    constexpr PlaneIdeal Translator::antiGeometric(const PointCenter& b) const noexcept { return {
        .x = -wx,
        .y = -wy,
        .z = -wz
    }; }


    constexpr Multivector Vector::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (b.s * x + b.xy * y + b.xz * z),
        .y = (b.s * y + b.yz * z - b.xy * x),
        .z = (b.s * z - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.i * z - b.wx * y),
        .wxz = (b.i * y + b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.i * x - b.wy * z),
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor Vector::antiGeometric(const Plane& b) const noexcept { return {
        .s = (b.x * x + b.y * y + b.z * z),
        .wx = b.w * x,
        .wy = b.w * y,
        .wz = b.w * z,
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y),
        .i = 0.0
    }; }

    constexpr Multivector Vector::antiGeometric(const Bivector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (b.xy * y + b.xz * z),
        .y = (b.yz * z - b.xy * x),
        .z = (-b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor Vector::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = -b.w * z,
        .xz = b.w * y,
        .yz = -b.w * x,
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Multivector Vector::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.s * x + b.xy * y + b.xz * z),
        .y = (b.s * y + b.yz * z - b.xy * x),
        .z = (b.s * z - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector Vector::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = b.s * x,
        .y = b.s * y,
        .z = b.s * z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector Vector::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = x,
        .y = y,
        .z = z,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Motor Vector::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Motor Vector::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = -z,
        .xz = y,
        .yz = -x,
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Quaternion Vector::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = (b.x * x + b.y * y + b.z * z),
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y)
    }; }

    constexpr Multivector Vector::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.xy * y + b.xz * z),
        .y = (b.yz * z - b.xy * x),
        .z = (-b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector Vector::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Vector Vector::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = b.i * x,
        .y = b.i * y,
        .z = b.i * z
    }; }

    constexpr BivectorBulk Vector::antiGeometric(const PointCenter& b) const noexcept { return {
        .xy = -z,
        .xz = y,
        .yz = -x
    }; }


    constexpr Multivector Point::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (-b.wx + b.s * x + b.xy * y + b.xz * z),
        .y = (-b.wy + b.s * y + b.yz * z - b.xy * x),
        .z = (-b.wz + b.s * z - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.i * z - b.wx * y),
        .wxz = (b.i * y + b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.i * x - b.wy * z),
        .xyz = (b.i + b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor Point::antiGeometric(const Plane& b) const noexcept { return {
        .s = (b.w + b.x * x + b.y * y + b.z * z),
        .wx = b.w * x,
        .wy = b.w * y,
        .wz = b.w * z,
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y),
        .i = 0.0
    }; }

    constexpr Multivector Point::antiGeometric(const Bivector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (-b.wx + b.xy * y + b.xz * z),
        .y = (-b.wy + b.yz * z - b.xy * x),
        .z = (-b.wz - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Motor Point::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = (b.z - b.w * z),
        .xz = (-b.y + b.w * y),
        .yz = (b.x - b.w * x),
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Multivector Point::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.s * x + b.xy * y + b.xz * z),
        .y = (b.s * y + b.yz * z - b.xy * x),
        .z = (b.s * z - b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector Point::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (-b.wx + b.s * x),
        .y = (-b.wy + b.s * y),
        .z = (-b.wz + b.s * z),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector Point::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = (x - b.wx),
        .y = (y - b.wy),
        .z = (z - b.wz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Motor Point::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = b.z,
        .xz = -b.y,
        .yz = b.x,
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Motor Point::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.z * y - b.y * z),
        .wy = (b.x * z - b.z * x),
        .wz = (b.y * x - b.x * y),
        .xy = (b.z - z),
        .xz = (y - b.y),
        .yz = (b.x - x),
        .i = (b.x * x + b.y * y + b.z * z)
    }; }

    constexpr Quaternion Point::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = (b.x * x + b.y * y + b.z * z),
        .xy = (b.x * y - b.y * x),
        .xz = (b.x * z - b.z * x),
        .yz = (b.y * z - b.z * y)
    }; }

    constexpr Multivector Point::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.xy * y + b.xz * z),
        .y = (b.yz * z - b.xy * x),
        .z = (-b.xz * x - b.yz * y),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.xz * y - b.xy * z - b.yz * x),
        .i = 0.0
    }; }

    constexpr Multivector Point::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .w = (b.wx * x + b.wy * y + b.wz * z),
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.wy * x - b.wx * y),
        .wxz = (b.wz * x - b.wx * z),
        .wyz = (b.wz * y - b.wy * z),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr ProjectivePoint Point::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = b.i * x,
        .y = b.i * y,
        .z = b.i * z,
        .w = b.i
    }; }

    constexpr BivectorBulk Point::antiGeometric(const PointCenter& b) const noexcept { return {
        .xy = -z,
        .xz = y,
        .yz = -x
    }; }


    constexpr Multivector PlaneIdeal::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.i * x + b.wy * z - b.wz * y),
        .y = (b.i * y + b.wz * x - b.wx * z),
        .z = (b.i * z + b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr BivectorBulk PlaneIdeal::antiGeometric(const Plane& b) const noexcept { return {
        .xy = b.w * z,
        .xz = -b.w * y,
        .yz = b.w * x
    }; }

    constexpr Multivector PlaneIdeal::antiGeometric(const Bivector& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Quaternion PlaneIdeal::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = (-b.x * x - b.y * y - b.z * z),
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z)
    }; }

    constexpr Multivector PlaneIdeal::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Multivector PlaneIdeal::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr Quaternion PlaneIdeal::antiGeometric(const Vector& b) const noexcept { return {
        .s = (-b.x * x - b.y * y - b.z * z),
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z)
    }; }

    constexpr Quaternion PlaneIdeal::antiGeometric(const Point& b) const noexcept { return {
        .s = (-b.x * x - b.y * y - b.z * z),
        .xy = (b.y * x - b.x * y),
        .xz = (b.z * x - b.x * z),
        .yz = (b.z * y - b.y * z)
    }; }

    constexpr Multivector PlaneIdeal::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.wy * z - b.wz * y),
        .y = (b.wz * x - b.wx * z),
        .z = (b.wx * y - b.wy * x),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.wx * x + b.wy * y + b.wz * z),
        .i = 0.0
    }; }

    constexpr PlaneIdeal PlaneIdeal::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = b.i * x,
        .y = b.i * y,
        .z = b.i * z
    }; }


    constexpr Quaternion BivectorBulk::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (b.i * xy - b.wx * xz - b.wy * yz),
        .xz = (b.i * xz + b.wx * xy - b.wz * yz),
        .yz = (b.i * yz + b.wy * xy + b.wz * xz)
    }; }

    constexpr PlaneIdeal BivectorBulk::antiGeometric(const Plane& b) const noexcept { return {
        .x = -b.w * yz,
        .y = b.w * xz,
        .z = -b.w * xy
    }; }

    constexpr Quaternion BivectorBulk::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz)
    }; }

    constexpr Multivector BivectorBulk::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz),
        .y = (b.z * yz - b.x * xy),
        .z = (-b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion BivectorBulk::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz)
    }; }

    constexpr Quaternion BivectorBulk::antiGeometric(const Translator& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz)
    }; }

    constexpr Multivector BivectorBulk::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz),
        .y = (b.z * yz - b.x * xy),
        .z = (-b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Multivector BivectorBulk::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * xy + b.z * xz),
        .y = (b.z * yz - b.x * xy),
        .z = (-b.x * xz - b.y * yz),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * yz + b.z * xy - b.y * xz),
        .i = 0.0
    }; }

    constexpr Quaternion BivectorBulk::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = (b.wx * yz + b.wz * xy - b.wy * xz),
        .xy = (-b.wx * xz - b.wy * yz),
        .xz = (b.wx * xy - b.wz * yz),
        .yz = (b.wy * xy + b.wz * xz)
    }; }

    constexpr BivectorBulk BivectorBulk::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .xy = b.i * xy,
        .xz = b.i * xz,
        .yz = b.i * yz
    }; }


    constexpr Motor BivectorWeight::antiGeometric(const Motor& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.i * wx + b.wy * wz - b.wz * wy),
        .wy = (b.i * wy + b.wz * wx - b.wx * wz),
        .wz = (b.i * wz + b.wx * wy - b.wy * wx),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector BivectorWeight::antiGeometric(const Plane& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = b.w * wz,
        .wxz = -b.w * wy,
        .wyz = b.w * wx,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Motor BivectorWeight::antiGeometric(const Bivector& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = (b.xz * wx + b.yz * wy),
        .xz = (b.yz * wz - b.xy * wx),
        .yz = (-b.xy * wy - b.xz * wz),
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector BivectorWeight::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = -b.w * wx,
        .y = -b.w * wy,
        .z = -b.w * wz,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Quaternion BivectorWeight::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy - b.s * wz),
        .xz = (b.s * wy + b.yz * wz - b.xy * wx),
        .yz = (-b.s * wx - b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor BivectorWeight::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = -b.s * wz,
        .xz = b.s * wy,
        .yz = -b.s * wx,
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Motor BivectorWeight::antiGeometric(const Translator& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = -wz,
        .xz = wy,
        .yz = -wx,
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr Multivector BivectorWeight::antiGeometric(const Vector& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector BivectorWeight::antiGeometric(const Point& b) const noexcept { return {
        .s = 0.0,
        .w = (b.x * wx + b.y * wy + b.z * wz),
        .x = -wx,
        .y = -wy,
        .z = -wz,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = (b.y * wx - b.x * wy),
        .wxz = (b.z * wx - b.x * wz),
        .wyz = (b.z * wy - b.y * wz),
        .xyz = 0.0,
        .i = 0.0
    }; }

    constexpr Multivector BivectorWeight::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = (b.y * wz - b.z * wy),
        .y = (b.z * wx - b.x * wz),
        .z = (b.x * wy - b.y * wx),
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = (b.x * wx + b.y * wy + b.z * wz),
        .i = 0.0
    }; }

    constexpr Quaternion BivectorWeight::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .s = (b.xy * wz + b.yz * wx - b.xz * wy),
        .xy = (b.xz * wx + b.yz * wy),
        .xz = (b.yz * wz - b.xy * wx),
        .yz = (-b.xy * wy - b.xz * wz)
    }; }

    constexpr Motor BivectorWeight::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .s = 0.0,
        .wx = (b.wy * wz - b.wz * wy),
        .wy = (b.wz * wx - b.wx * wz),
        .wz = (b.wx * wy - b.wy * wx),
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .i = (-b.wx * wx - b.wy * wy - b.wz * wz)
    }; }

    constexpr BivectorWeight BivectorWeight::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .wx = b.i * wx,
        .wy = b.i * wy,
        .wz = b.i * wz
    }; }

    constexpr PlaneIdeal BivectorWeight::antiGeometric(const PointCenter& b) const noexcept { return {
        .x = -wx,
        .y = -wy,
        .z = -wz
    }; }


    constexpr Motor PseudoScalar::antiGeometric(const Motor& b) const noexcept { return {
        .s = b.s * i,
        .wx = b.wx * i,
        .wy = b.wy * i,
        .wz = b.wz * i,
        .xy = b.xy * i,
        .xz = b.xz * i,
        .yz = b.yz * i,
        .i = b.i * i
    }; }

    constexpr Plane PseudoScalar::antiGeometric(const Plane& b) const noexcept { return {
        .x = b.x * i,
        .y = b.y * i,
        .z = b.z * i,
        .w = b.w * i
    }; }

    constexpr Bivector PseudoScalar::antiGeometric(const Bivector& b) const noexcept { return {
        .wx = b.wx * i,
        .wy = b.wy * i,
        .wz = b.wz * i,
        .xy = b.xy * i,
        .xz = b.xz * i,
        .yz = b.yz * i
    }; }

    constexpr ProjectivePoint PseudoScalar::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .x = b.x * i,
        .y = b.y * i,
        .z = b.z * i,
        .w = b.w * i
    }; }

    constexpr Quaternion PseudoScalar::antiGeometric(const Quaternion& b) const noexcept { return {
        .s = b.s * i,
        .xy = b.xy * i,
        .xz = b.xz * i,
        .yz = b.yz * i
    }; }

    constexpr ProjectiveTranslator PseudoScalar::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .s = b.s * i,
        .wx = b.wx * i,
        .wy = b.wy * i,
        .wz = b.wz * i
    }; }

    constexpr ProjectiveTranslator PseudoScalar::antiGeometric(const Translator& b) const noexcept { return {
        .s = i,
        .wx = b.wx * i,
        .wy = b.wy * i,
        .wz = b.wz * i
    }; }

    constexpr Vector PseudoScalar::antiGeometric(const Vector& b) const noexcept { return {
        .x = b.x * i,
        .y = b.y * i,
        .z = b.z * i
    }; }

    constexpr ProjectivePoint PseudoScalar::antiGeometric(const Point& b) const noexcept { return {
        .x = b.x * i,
        .y = b.y * i,
        .z = b.z * i,
        .w = i
    }; }

    constexpr PlaneIdeal PseudoScalar::antiGeometric(const PlaneIdeal& b) const noexcept { return {
        .x = b.x * i,
        .y = b.y * i,
        .z = b.z * i
    }; }

    constexpr BivectorBulk PseudoScalar::antiGeometric(const BivectorBulk& b) const noexcept { return {
        .xy = b.xy * i,
        .xz = b.xz * i,
        .yz = b.yz * i
    }; }

    constexpr BivectorWeight PseudoScalar::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .wx = b.wx * i,
        .wy = b.wy * i,
        .wz = b.wz * i
    }; }

    constexpr PseudoScalar PseudoScalar::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .i = b.i * i
    }; }

    constexpr ProjectivePoint PseudoScalar::antiGeometric(const PointCenter& b) const noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = i
    }; }


    constexpr Multivector PointCenter::antiGeometric(const Motor& b) const noexcept { return {
        .s = 0.0,
        .w = 0.0,
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz,
        .wx = 0.0,
        .wy = 0.0,
        .wz = 0.0,
        .xy = 0.0,
        .xz = 0.0,
        .yz = 0.0,
        .wxy = 0.0,
        .wxz = 0.0,
        .wyz = 0.0,
        .xyz = b.i,
        .i = 0.0
    }; }

    constexpr double PointCenter::antiGeometric(const Plane& b) const noexcept { return b.w; }

    constexpr PlaneIdeal PointCenter::antiGeometric(const Bivector& b) const noexcept { return {
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz
    }; }

    constexpr BivectorBulk PointCenter::antiGeometric(const ProjectivePoint& b) const noexcept { return {
        .xy = b.z,
        .xz = -b.y,
        .yz = b.x
    }; }

    constexpr PlaneIdeal PointCenter::antiGeometric(const ProjectiveTranslator& b) const noexcept { return {
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz
    }; }

    constexpr PlaneIdeal PointCenter::antiGeometric(const Translator& b) const noexcept { return {
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz
    }; }

    constexpr BivectorBulk PointCenter::antiGeometric(const Vector& b) const noexcept { return {
        .xy = b.z,
        .xz = -b.y,
        .yz = b.x
    }; }

    constexpr BivectorBulk PointCenter::antiGeometric(const Point& b) const noexcept { return {
        .xy = b.z,
        .xz = -b.y,
        .yz = b.x
    }; }

    constexpr PlaneIdeal PointCenter::antiGeometric(const BivectorWeight& b) const noexcept { return {
        .x = -b.wx,
        .y = -b.wy,
        .z = -b.wz
    }; }

    constexpr ProjectivePoint PointCenter::antiGeometric(const PseudoScalar& b) const noexcept { return {
        .x = 0.0,
        .y = 0.0,
        .z = 0.0,
        .w = b.i
    }; }


}