// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.AntiReverseOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::antiReversed() const noexcept { return {.s = s, .w = -w, .x = -x, .y = -y, .z = -z, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .wxy = wxy, .wxz = wxz, .wyz = wyz, .xyz = xyz, .i = i}; }
    constexpr Motor Motor::antiReversed() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .i = i}; }
    constexpr Plane Plane::antiReversed() const noexcept { return {.x = -x, .y = -y, .z = -z, .w = -w}; }
    constexpr Bivector Bivector::antiReversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectivePoint ProjectivePoint::antiReversed() const noexcept { return {.x = x, .y = y, .z = z, .w = w}; }
    constexpr Quaternion Quaternion::antiReversed() const noexcept { return {.s = s, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectiveTranslator ProjectiveTranslator::antiReversed() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Translator Translator::antiReversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Vector Vector::antiReversed() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr Point Point::antiReversed() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr PlaneIdeal PlaneIdeal::antiReversed() const noexcept { return {.x = -x, .y = -y, .z = -z}; }
    constexpr BivectorBulk BivectorBulk::antiReversed() const noexcept { return {.xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr BivectorWeight BivectorWeight::antiReversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr PseudoScalar PseudoScalar::antiReversed() const noexcept { return {.i = i}; }
    constexpr PointCenter PointCenter::antiReversed() const noexcept { return {}; }
}