// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.AntiReverseOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::antiReverse() const noexcept { return {.s = s, .w = -w, .x = -x, .y = -y, .z = -z, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .wxy = wxy, .wxz = wxz, .wyz = wyz, .xyz = xyz, .i = i}; }
    constexpr Motor Motor::antiReverse() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .i = i}; }
    constexpr Plane Plane::antiReverse() const noexcept { return {.x = -x, .y = -y, .z = -z, .w = -w}; }
    constexpr Bivector Bivector::antiReverse() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectivePoint ProjectivePoint::antiReverse() const noexcept { return {.x = x, .y = y, .z = z, .w = w}; }
    constexpr Quaternion Quaternion::antiReverse() const noexcept { return {.s = s, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectiveTranslator ProjectiveTranslator::antiReverse() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Translator Translator::antiReverse() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Vector Vector::antiReverse() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr Point Point::antiReverse() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr PlaneIdeal PlaneIdeal::antiReverse() const noexcept { return {.x = -x, .y = -y, .z = -z}; }
    constexpr BivectorBulk BivectorBulk::antiReverse() const noexcept { return {.xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr BivectorWeight BivectorWeight::antiReverse() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr PseudoScalar PseudoScalar::antiReverse() const noexcept { return {.i = i}; }
    constexpr PointCenter PointCenter::antiReverse() const noexcept { return {}; }
}