// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.BulkOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::bulk() const noexcept { return {.s = s, .w = 0.0, .x = x, .y = y, .z = z, .wx = 0.0, .wy = 0.0, .wz = 0.0, .xy = xy, .xz = xz, .yz = yz, .wxy = 0.0, .wxz = 0.0, .wyz = 0.0, .xyz = xyz, .i = 0.0}; }
    constexpr Quaternion Motor::bulk() const noexcept { return {.s = s, .xy = xy, .xz = xz, .yz = yz}; }
    constexpr PlaneIdeal Plane::bulk() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr BivectorBulk Bivector::bulk() const noexcept { return {.xy = xy, .xz = xz, .yz = yz}; }
    constexpr ProjectivePoint ProjectivePoint::bulk() const noexcept { return {.x = 0.0, .y = 0.0, .z = 0.0, .w = w}; }
    constexpr Quaternion Quaternion::bulk() const noexcept { return {.s = s, .xy = xy, .xz = xz, .yz = yz}; }
    constexpr double Translator::bulk() const noexcept { return 1.0; }
    constexpr PointCenter Point::bulk() const noexcept { return {}; }
    constexpr PlaneIdeal PlaneIdeal::bulk() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr BivectorBulk BivectorBulk::bulk() const noexcept { return {.xy = xy, .xz = xz, .yz = yz}; }
    constexpr PointCenter PointCenter::bulk() const noexcept { return {}; }
}