// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.BivectorWeightOpsGenerator

namespace pga3d {

    [[nodiscard]] constexpr Translator BivectorWeight::exp() const noexcept {
        return Translator{
            .wx = wx,
            .wy = wy,
            .wz = wz,
        };
    }
}