// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <cmath>
#include "types.h"
#include "opsNorm.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.BivectorBulkOpsGenerator

namespace pga3d {

    [[nodiscard]] inline Quaternion BivectorBulk::exp() const noexcept {
        const double len = bulkNorm();
        const double cos = std::cos(len);

        const double sinDivLen = (len > 1e-5)
            ? (std::sin(len) / len)
            : (1.0 - (len * len) / 6.0);

        return Quaternion{
            .s = cos,
            .xy = sinDivLen * xy,
            .xz = sinDivLen * xz,
            .yz = sinDivLen * yz,
        };
    }
}