// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.DualOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::dual() const noexcept { return {.s = i, .w = xyz, .x = -wyz, .y = wxz, .z = -wxy, .wx = yz, .wy = -xz, .wz = xy, .xy = wz, .xz = -wy, .yz = wx, .wxy = -z, .wxz = y, .wyz = -x, .xyz = w, .i = s}; }
    constexpr Motor Motor::dual() const noexcept { return {.s = i, .wx = yz, .wy = -xz, .wz = xy, .xy = wz, .xz = -wy, .yz = wx, .i = s}; }
    constexpr ProjectivePoint Plane::dual() const noexcept { return {.x = x, .y = y, .z = z, .w = w}; }
    constexpr Bivector Bivector::dual() const noexcept { return {.wx = yz, .wy = -xz, .wz = xy, .xy = wz, .xz = -wy, .yz = wx}; }
    constexpr Plane ProjectivePoint::dual() const noexcept { return {.x = x, .y = y, .z = z, .w = w}; }
    constexpr Motor Quaternion::dual() const noexcept { return {.s = 0.0, .wx = yz, .wy = -xz, .wz = xy, .xy = 0.0, .xz = 0.0, .yz = 0.0, .i = s}; }
    constexpr Motor ProjectiveTranslator::dual() const noexcept { return {.s = 0.0, .wx = 0.0, .wy = 0.0, .wz = 0.0, .xy = wz, .xz = -wy, .yz = wx, .i = s}; }
    constexpr Motor Translator::dual() const noexcept { return {.s = 0.0, .wx = 0.0, .wy = 0.0, .wz = 0.0, .xy = wz, .xz = -wy, .yz = wx, .i = 1.0}; }
    constexpr PlaneIdeal Vector::dual() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr Plane Point::dual() const noexcept { return {.x = x, .y = y, .z = z, .w = 1.0}; }
    constexpr Vector PlaneIdeal::dual() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr BivectorWeight BivectorBulk::dual() const noexcept { return {.wx = yz, .wy = -xz, .wz = xy}; }
    constexpr BivectorBulk BivectorWeight::dual() const noexcept { return {.xy = wz, .xz = -wy, .yz = wx}; }
    constexpr double PseudoScalar::dual() const noexcept { return i; }
    constexpr Plane PointCenter::dual() const noexcept { return {.x = 0.0, .y = 0.0, .z = 0.0, .w = 1.0}; }
}