// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseOpGenerator

namespace pga3d {
    constexpr Multivector Multivector::reversed() const noexcept { return {.s = s, .w = w, .x = x, .y = y, .z = z, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .wxy = -wxy, .wxz = -wxz, .wyz = -wyz, .xyz = -xyz, .i = i}; }
    constexpr Motor Motor::reversed() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz, .i = i}; }
    constexpr Plane Plane::reversed() const noexcept { return {.x = x, .y = y, .z = z, .w = w}; }
    constexpr Bivector Bivector::reversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectivePoint ProjectivePoint::reversed() const noexcept { return {.x = -x, .y = -y, .z = -z, .w = -w}; }
    constexpr Quaternion Quaternion::reversed() const noexcept { return {.s = s, .xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr ProjectiveTranslator ProjectiveTranslator::reversed() const noexcept { return {.s = s, .wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Translator Translator::reversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr Vector Vector::reversed() const noexcept { return {.x = -x, .y = -y, .z = -z}; }
    constexpr ProjectivePoint Point::reversed() const noexcept { return {.x = -x, .y = -y, .z = -z, .w = -1.0}; }
    constexpr PlaneIdeal PlaneIdeal::reversed() const noexcept { return {.x = x, .y = y, .z = z}; }
    constexpr BivectorBulk BivectorBulk::reversed() const noexcept { return {.xy = -xy, .xz = -xz, .yz = -yz}; }
    constexpr BivectorWeight BivectorWeight::reversed() const noexcept { return {.wx = -wx, .wy = -wy, .wz = -wz}; }
    constexpr PseudoScalar PseudoScalar::reversed() const noexcept { return {.i = i}; }
    constexpr ProjectivePoint PointCenter::reversed() const noexcept { return {.x = 0.0, .y = 0.0, .z = 0.0, .w = -1.0}; }
}