#pragma once

#include "types.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.TranslatorOpsGenerator

namespace pga3d {

    [[nodiscard]] constexpr Translator Translator::addVector(const Vector& v) noexcept { return {.wx = v.x, .wy = v.y, .wz = v.z}; }

    [[nodiscard]] constexpr BivectorWeight Translator::log() const noexcept {
        return BivectorWeight {
            .wx = wx,
            .wy = wy,
            .wz = wz,
        };
    }

    [[nodiscard]] constexpr Translator Translator::pow(double p) const noexcept {
       return (log() * p).exp();
    }
}