// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <algorithm>
#include "Vector.h"

// generated by com.github.kright.pga3d.codegen.cpp.binops.VectorOpsGenerator

namespace pga3d {

    [[nodiscard]] inline Vector Vector::min(const Vector& other) const noexcept {
        return Vector{
            .x = std::min(x, other.x),
            .y = std::min(y, other.y),
            .z = std::min(z, other.z),
        };
    }

    [[nodiscard]] inline Vector Vector::max(const Vector& other) const noexcept {
        return Vector{
            .x = std::max(x, other.x),
            .y = std::max(y, other.y),
            .z = std::max(z, other.z),
        };
    }

    [[nodiscard]] inline Vector Vector::clamp(const Vector& minV, const Vector& maxV) const noexcept {
        return Vector{
            .x = std::clamp(x, minV.x, maxV.x),
            .y = std::clamp(y, minV.y, maxV.y),
            .z = std::clamp(z, minV.z, maxV.z),
        };
    }
}