// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "types.h"
#include "TranslatorWithQuaternion.h"
#include "opsQuaternion.h"
#include "opsTranslator.h"
#include "opsMotor.h"
#include "opsBivector.h"
#include "opsBivectorBulk.h"
#include "opsBivectorWeight.h"
#include "opsPoint.h"
#include "opsVector.h"
#include "opsDual.h"
#include "opsWeight.h"
#include "opsBulk.h"
#include "opsReverse.h"
#include "opsAntiReverse.h"
#include "opsTo.h"
#include "opsArithmetic.h"
#include "opsNorm.h"
#include "opsStr.h"
#include "opsProject.h"
#include "opsGeometric.h"
#include "opsAntiGeometric.h"
#include "opsDot.h"
#include "opsAntiDot.h"
#include "opsWedge.h"
#include "opsAntiWedge.h"
#include "opsSandwich.h"
#include "opsReverseSandwich.h"
#include "opsCross.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp