#pragma once

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp

#include "types.h"

#include "ops_dual.h"
#include "ops_weight.h"
#include "ops_bulk.h"
#include "ops_reverse.h"
#include "ops_antiReverse.h"
#include "ops_geometric.h"
#include "ops_wedge.h"
#include "ops_dot.h"
#include "ops_antiGeometric.h"
#include "ops_antiWedge.h"
#include "ops_antiDot.h"
#include "ops_to.h"
#include "ops_arithmetic.h"
#include "ops_norm.h"
#include "ops_str.h"