// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <array>
#include <span>
#include <type_traits>
#include "typesForward.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp

namespace pga3d {
    struct Plane {
        // generated by com.github.kright.pga3d.codegen.cpp.ops.StructFieldsGenerator

        double x = 0.0;
        double y = 0.0;
        double z = 0.0;
        double w = 0.0;

        static constexpr int componentsCount = 4;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept { return { x, y, z, w }; }
        [[nodiscard]] static constexpr Plane from(const std::span<double, componentsCount>& values) noexcept { return { .x = values[0], .y = values[1], .z = values[2], .w = values[3] }; }

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DualOpGenerator

        [[nodiscard]] constexpr ProjectivePoint dual() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WeightOpGenerator

        [[nodiscard]] constexpr Plane weight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.BulkOpGenerator

        [[nodiscard]] constexpr PlaneIdeal bulk() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseOpGenerator

        [[nodiscard]] constexpr Plane reverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiReverseOpGenerator

        [[nodiscard]] constexpr Plane antiReverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ConversionOpGenerator

        [[nodiscard]] constexpr Multivector toMultivector() const noexcept;
        [[nodiscard]] constexpr PlaneIdeal toPlaneIdealUnsafe() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ArithmeticsGenerator

        [[nodiscard]] constexpr Plane madd(const Plane& other, double mult) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.NormOpGenerator

        [[nodiscard]] constexpr double normSquare() const noexcept;
        [[nodiscard]] inline double norm() const noexcept;
        [[nodiscard]] inline Plane normalizedByNorm() const noexcept;
        [[nodiscard]] constexpr double bulkNormSquare() const noexcept;
        [[nodiscard]] inline double bulkNorm() const noexcept;
        [[nodiscard]] inline Plane normalizedByBulk() const noexcept;
        [[nodiscard]] constexpr double weightNormSquare() const noexcept;
        [[nodiscard]] inline double weightNorm() const noexcept;
        [[nodiscard]] inline Plane normalizedByWeight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.GeometricOpGenerator

        [[nodiscard]] constexpr Multivector geometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr Vector geometric(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiGeometricOpGenerator

        [[nodiscard]] constexpr Multivector antiGeometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr BivectorBulk antiGeometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal antiGeometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr Plane antiGeometric(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr double antiGeometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DotOpGenerator

        [[nodiscard]] constexpr Multivector dot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr double dot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Bivector dot(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight dot(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Bivector dot(const Point& b) const noexcept;
        [[nodiscard]] constexpr double dot(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal dot(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr Vector dot(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr BivectorBulk dot(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiDotOpGenerator

        [[nodiscard]] constexpr Multivector antiDot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar antiDot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Bivector antiDot(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Bivector antiDot(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Bivector antiDot(const Point& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr Plane antiDot(const PseudoScalar& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WedgeOpGenerator

        [[nodiscard]] constexpr Multivector wedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Bivector wedge(const Plane& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint wedge(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Multivector wedge(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Multivector wedge(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Multivector wedge(const Translator& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const Vector& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const Point& b) const noexcept;
        [[nodiscard]] constexpr Bivector wedge(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint wedge(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Vector wedge(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiWedgeOpGenerator

        [[nodiscard]] constexpr Plane antiWedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Vector& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.SandwichOpGenerator

        [[nodiscard]] constexpr Motor sandwich(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane sandwich(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Bivector sandwich(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor sandwich(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator sandwich(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator sandwich(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector sandwich(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane sandwich(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Bivector sandwich(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight sandwich(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar sandwich(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseSandwichOpGenerator

        [[nodiscard]] constexpr Motor reverseSandwich(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane reverseSandwich(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Bivector reverseSandwich(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor reverseSandwich(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator reverseSandwich(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator reverseSandwich(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector reverseSandwich(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane reverseSandwich(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Bivector reverseSandwich(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight reverseSandwich(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar reverseSandwich(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.CrossOpGenerator

        [[nodiscard]] constexpr Multivector cross(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Bivector cross(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar cross(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal cross(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const Translator& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar cross(const Vector& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar cross(const Point& b) const noexcept;
        [[nodiscard]] constexpr Bivector cross(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal cross(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar cross(const PointCenter& b) const noexcept;
    };

    static_assert(std::is_trivially_copyable_v<Plane>);
    static_assert(sizeof(Plane) == 8 * Plane::componentsCount, "Plane must be exactly 32 bytes");
}