// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include <array>
#include <span>
#include <type_traits>
#include "typesForward.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp

namespace pga3d {
    struct ProjectiveTranslator {
        // generated by com.github.kright.pga3d.codegen.cpp.ops.StructFieldsGenerator

        double s = 0.0;
        double wx = 0.0;
        double wy = 0.0;
        double wz = 0.0;

        static constexpr int componentsCount = 4;

        [[nodiscard]] constexpr std::array<double, componentsCount> toArray() const noexcept { return { s, wx, wy, wz }; }
        [[nodiscard]] static constexpr ProjectiveTranslator from(const std::array<double, componentsCount>& values) noexcept { return { .s = values[0], .wx = values[1], .wy = values[2], .wz = values[3] }; }
        [[nodiscard]] static constexpr ProjectiveTranslator from(const std::span<double, componentsCount>& values) noexcept { return { .s = values[0], .wx = values[1], .wy = values[2], .wz = values[3] }; }

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DualOpGenerator

        [[nodiscard]] constexpr Motor dual() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WeightOpGenerator

        [[nodiscard]] constexpr BivectorWeight weight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.BulkOpGenerator

        [[nodiscard]] constexpr double bulk() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseOpGenerator

        [[nodiscard]] constexpr ProjectiveTranslator reverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiReverseOpGenerator

        [[nodiscard]] constexpr ProjectiveTranslator antiReverse() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ConversionOpGenerator

        [[nodiscard]] constexpr Multivector toMultivector() const noexcept;
        [[nodiscard]] constexpr Motor toMotor() const noexcept;
        [[nodiscard]] constexpr Bivector toBivectorUnsafe() const noexcept;
        [[nodiscard]] constexpr Quaternion toQuaternionUnsafe() const noexcept;
        [[nodiscard]] constexpr Translator toTranslatorUnsafe() const noexcept;
        [[nodiscard]] constexpr BivectorWeight toBivectorWeightUnsafe() const noexcept;
        [[nodiscard]] constexpr Translator toTranslator() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ArithmeticsGenerator

        [[nodiscard]] constexpr ProjectiveTranslator madd(const ProjectiveTranslator& other, double mult) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.NormOpGenerator

        [[nodiscard]] constexpr double normSquare() const noexcept;
        [[nodiscard]] inline double norm() const noexcept;
        [[nodiscard]] inline ProjectiveTranslator normalizedByNorm() const noexcept;
        [[nodiscard]] constexpr double bulkNormSquare() const noexcept;
        [[nodiscard]] inline double bulkNorm() const noexcept;
        [[nodiscard]] inline ProjectiveTranslator normalizedByBulk() const noexcept;
        [[nodiscard]] constexpr double weightNormSquare() const noexcept;
        [[nodiscard]] inline double weightNorm() const noexcept;
        [[nodiscard]] inline ProjectiveTranslator normalizedByWeight() const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.GeometricOpGenerator

        [[nodiscard]] constexpr Motor geometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint geometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator geometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator geometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector geometric(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint geometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr Multivector geometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Motor geometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight geometric(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar geometric(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint geometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiGeometricOpGenerator

        [[nodiscard]] constexpr Motor antiGeometric(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Quaternion antiGeometric(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const Point& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiGeometric(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Quaternion antiGeometric(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Motor antiGeometric(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator antiGeometric(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal antiGeometric(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.DotOpGenerator

        [[nodiscard]] constexpr Motor dot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Bivector dot(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint dot(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor dot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator dot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator dot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector dot(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint dot(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane dot(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr BivectorBulk dot(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight dot(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar dot(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint dot(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiDotOpGenerator

        [[nodiscard]] constexpr Motor antiDot(const Motor& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiDot(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr BivectorBulk antiDot(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiDot(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Multivector antiDot(const Point& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint antiDot(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Motor antiDot(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator antiDot(const PseudoScalar& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.WedgeOpGenerator

        [[nodiscard]] constexpr Motor wedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Multivector wedge(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Motor wedge(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint wedge(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor wedge(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator wedge(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator wedge(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector wedge(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint wedge(const Point& b) const noexcept;
        [[nodiscard]] constexpr Multivector wedge(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Motor wedge(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight wedge(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar wedge(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint wedge(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.AntiWedgeOpGenerator

        [[nodiscard]] constexpr ProjectiveTranslator antiWedge(const Motor& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const Vector& b) const noexcept;
        [[nodiscard]] constexpr Plane antiWedge(const Point& b) const noexcept;
        [[nodiscard]] constexpr double antiWedge(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator antiWedge(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr PlaneIdeal antiWedge(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.SandwichOpGenerator

        [[nodiscard]] constexpr Motor sandwich(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane sandwich(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Bivector sandwich(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor sandwich(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator sandwich(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator sandwich(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector sandwich(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane sandwich(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Bivector sandwich(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight sandwich(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar sandwich(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint sandwich(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.ReverseSandwichOpGenerator

        [[nodiscard]] constexpr Motor reverseSandwich(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane reverseSandwich(const Plane& b) const noexcept;
        [[nodiscard]] constexpr Bivector reverseSandwich(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr Motor reverseSandwich(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator reverseSandwich(const ProjectiveTranslator& b) const noexcept;
        [[nodiscard]] constexpr ProjectiveTranslator reverseSandwich(const Translator& b) const noexcept;
        [[nodiscard]] constexpr Vector reverseSandwich(const Vector& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane reverseSandwich(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr Bivector reverseSandwich(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight reverseSandwich(const BivectorWeight& b) const noexcept;
        [[nodiscard]] constexpr PseudoScalar reverseSandwich(const PseudoScalar& b) const noexcept;
        [[nodiscard]] constexpr ProjectivePoint reverseSandwich(const PointCenter& b) const noexcept;

        // generated by com.github.kright.pga3d.codegen.cpp.ops.CrossOpGenerator

        [[nodiscard]] constexpr BivectorWeight cross(const Motor& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const Plane& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const Bivector& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const ProjectivePoint& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const Quaternion& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const Point& b) const noexcept;
        [[nodiscard]] constexpr Plane cross(const PlaneIdeal& b) const noexcept;
        [[nodiscard]] constexpr BivectorWeight cross(const BivectorBulk& b) const noexcept;
        [[nodiscard]] constexpr Vector cross(const PointCenter& b) const noexcept;
    };

    static_assert(std::is_trivially_copyable_v<ProjectiveTranslator>);
    static_assert(sizeof(ProjectiveTranslator) == 8 * ProjectiveTranslator::componentsCount, "ProjectiveTranslator must be exactly 32 bytes");
}