// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "Motor.h"
#include "Quaternion.h"
#include "Translator.h"

// generated by com.github.kright.pga3d.codegen.cpp.ops.TranslatorWithQuaternionGenerator

namespace pga3d {

    struct TranslatorWithQuaternion {
        Translator translator{};
        Quaternion quaternion{};

        [[nodiscard]] constexpr Motor toMotor() const noexcept { return translator.geometric(quaternion); }

        [[nodiscard]] constexpr QuaternionWithTranslator reverse() const noexcept;

        [[nodiscard]] constexpr QuaternionWithTranslator toQuaternionWithTranslator() const noexcept;

        [[nodiscard]] static constexpr TranslatorWithQuaternion id() noexcept { return { .translator = Translator::id(), .quaternion = Quaternion::id() }; }
    };

    struct QuaternionWithTranslator {
        Quaternion quaternion{};
        Translator translator{};

        [[nodiscard]] constexpr Motor toMotor() const noexcept { return quaternion.geometric(translator); }

        [[nodiscard]] constexpr TranslatorWithQuaternion reverse() const noexcept;

        [[nodiscard]] constexpr TranslatorWithQuaternion toTranslatorWithQuaternion() const noexcept;

        [[nodiscard]] static constexpr QuaternionWithTranslator id() noexcept { return { .quaternion = Quaternion::id(), .translator = Translator::id() }; }
    };

    [[nodiscard]] constexpr QuaternionWithTranslator TranslatorWithQuaternion::reverse() const noexcept { return { .quaternion = quaternion.reverse(), .translator = translator.reverse() }; }
    [[nodiscard]] constexpr QuaternionWithTranslator TranslatorWithQuaternion::toQuaternionWithTranslator() const noexcept { return { .quaternion = quaternion, .translator = quaternion.reverse().sandwich(translator).toTranslator() }; };
    [[nodiscard]] constexpr TranslatorWithQuaternion QuaternionWithTranslator::reverse() const noexcept { return { .translator = translator.reverse(), .quaternion = quaternion.reverse() }; }
    [[nodiscard]] constexpr TranslatorWithQuaternion QuaternionWithTranslator::toTranslatorWithQuaternion() const noexcept { return { .translator = quaternion.sandwich(translator).toTranslator(), .quaternion = quaternion }; };
}