// Copyright (c) 2025 Igor Slobodskov
// SPDX-License-Identifier: MIT

#pragma once

#include "Multivector.h"
#include "Motor.h"
#include "Plane.h"
#include "Bivector.h"
#include "ProjectivePoint.h"
#include "Quaternion.h"
#include "ProjectiveTranslator.h"
#include "Translator.h"
#include "Vector.h"
#include "Point.h"
#include "PlaneIdeal.h"
#include "BivectorBulk.h"
#include "BivectorWeight.h"
#include "PseudoScalar.h"
#include "PointCenter.h"
#include "TranslatorWithQuaternion.h"

// generated by com.github.kright.pga3d.codegen.cpp.Pga3dCodeGenCpp